apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: performance
spec:
  type: filebeat
  version: 8.13.4
  config:
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /jmeter/report*.csv
        fields:
          type: jmeter_csv
        fields_under_root: true
      - type: log
        enabled: true
        paths:
          - /jmeter/jmeter*.log
        fields:
          type: jmeter_log
        fields_under_root: true
      - type: log
        enabled: true
        paths:
          - /fastapp_logs/*.log
        fields:
          type: fastapp
        fields_under_root: true
    output.logstash:
      hosts: ["logstash-ls-beats:5044"]
  daemonSet:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            volumeMounts:
              - name: jmeter-logs
                mountPath: /jmeter
              - name: fastapp-logs-volume
                mountPath: /fastapp_logs
        volumes:
          - name: jmeter-logs
            persistentVolumeClaim:
              claimName: jmeter-logs-pvc
          - name: fastapp-logs-volume
            persistentVolumeClaim:
              claimName: fastapp-logs-pvc  