# Deployment for FastAPI application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapp
  namespace: performance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapp
  template:
    metadata:
      labels:
        app: fastapp
    spec:
      containers:
        - name: fastapp
          image: youketero/fastapp:latest
          ports:
            - containerPort: 8000
          volumeMounts:                
            - mountPath: /logs          
              name: fastapp-logs-volume
          env:
            - name: USE_MOCK
              value: "true"
      volumes:                    
        - name: fastapp-logs-volume
          persistentVolumeClaim:
            claimName: fastapp-logs-pvc             
---
apiVersion: v1
kind: Service
metadata:
  name: fastapp
  namespace: performance
spec:
  type: NodePort
  selector:
    app: fastapp
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
