---
# ServiceAccount для Metricbeat
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: performance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
rules:
- apiGroups: [""]
  resources:
    - nodes
    - namespaces
    - events
    - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
    - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - statefulsets
    - deployments
    - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
    - nodes/stats
  verbs: ["get"]
- nonResourceURLs:
    - /metrics
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: performance
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat
  namespace: performance
spec:
  type: metricbeat
  version: 8.13.4
  elasticsearchRef:
    name: elasticsearch
    namespace: performance
  # kibanaRef:
    # name: kibana
    # namespace: performance
  config:
    metricbeat:
      outputs:
        elasticsearch:
          hosts: ["https://elasticsearch-es-http.performance.svc.cluster.local:9200"]
          username: "${{ELASTICSEARCH_ES_USER}"
          password: "${ELASTICSEARCH_ES_PASSWORD}"
          index: "metrics-%{+yyyy.MM.dd}"
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints:
            default_config: {}
            enabled: "true"
      modules:
      - module: system
        period: 10s
        metricsets:
        - cpu
        - load
        - memory
        - network
        # - process
        # - process_summary
        # process:
          # include_top_n:
            # by_cpu: 5
            # by_memory: 5
        # processes:
        # - ".*"
      - module: system
        period: 1m
        metricsets:
        - filesystem
        - fsstat
        processors:
        - drop_event:
            when:
              regexp:
                system:
                  filesystem:
                    mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib)($|/)
      - module: kubernetes
        period: 10s
        node: ${NODE_NAME}
        hosts:
        - https://${NODE_NAME}:10250
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        ssl:
          verification_mode: none
        metricsets:
        - node
        - system
        - pod
        - container
        - volume
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: metricbeat
        automountServiceAccountToken: true
        hostNetwork: false
        terminationGracePeriodSeconds: 30
        securityContext:
          runAsUser: 0
        containers:
        - name: metricbeat
          image: docker.elastic.co/beats/metricbeat:8.13.4
          args:
          - -e
          - -c
          - /etc/beat.yml
          - --system.hostfs=/hostfs
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          volumeMounts:
          - name: proc
            mountPath: /hostfs/proc
            readOnly: true
          - name: cgroup
            mountPath: /hostfs/sys/fs/cgroup
            readOnly: true
          - name: dockersock
            mountPath: /var/run/docker.sock
        volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
