apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:  
  pipelines:
  - pipeline.id: main
    config.string: |
      input {
        beats {
          port => 5044
        }
      }
      filter {
        if "k6_log" in [type]{
          csv {
            separator => ","
            skip_header => "true"
            columns => ["metric_name","timestamp","metric_value","check,error","error_code","expected_response","mess","group","method","name","proto","scenario","service","status","subproto","tls_version","url","extra_tags"]
          }
          mutate{
            convert => {
                "timestamp" => "integer"
                "metric_value" => "integer"
                "expected_response" => "boolean"
                "metric_name" => "string"
                "status"=> "integer"
              }
          }
        }
      }
      output {
        elasticsearch {
          hosts => ["${ELASTICSEARCH_ES_HOSTS}"]
          user => "${ELASTICSEARCH_ES_USER}"
          password => "${ELASTICSEARCH_ES_PASSWORD}"
          ssl_certificate_authorities => "${ELASTICSEARCH_ES_SSL_CERTIFICATE_AUTHORITY}"
          index => "%{[type]}-%{+YYYY.MM.dd}"
        }
        stdout { codec => json }
      }