# Service for jmeter slave. Need to access from master to slave jmeter nodes
apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  namespace: performance
  labels:
    jmeter_mode: slave
spec:
  clusterIP: None  # headless service
  ports:
    - port: 1099
      name: jmeter
      targetPort: 1099
    - port: 50000
      name: rmi
      targetPort: 50000
    - port: 4445
      name: stoptest
      targetPort: 4445
  selector:
    jmeter_mode: slave
