apiVersion: v1
kind: Service
metadata:
  name: fastapp
  namespace: performance
spec:
  type: NodePort
  selector:
    app: fastapp
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
