jenkins:
  systemMessage: "Jenkins on k8s"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true

unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: |
      def jobs = [
          [name: 'deploy_eck', path: 'jenkins/jobs/deploy_eck.Jenkinsfile'],
          [name: 'stop_eck', path: 'jenkins/jobs/stop_eck.Jenkinsfile'],
          [name: 'deploy_jmeter_cluster', path: 'jenkins/jobs/deploy_jmeter_cluster.Jenkinsfile'],
          [name: 'stop_jmeter_cluster', path: 'jenkins/jobs/stop_jmeter_cluster.Jenkinsfile'],
          [name: 'start_jmeter_test', path: 'jenkins/jobs/start_jmeter_test.Jenkinsfile'],
          [name: 'stop_jmeter_test', path: 'jenkins/jobs/stop_jmeter_test.Jenkinsfile']
      ]
      jobs.each { j ->
          pipelineJob(j.name) {
              description("Pipeline job ${j.name} created automatically by Seed Job")
              definition {
                  cpsScm {
                      scm {
                          git {
                              remote { url 'https://github.com/youketero/k8s_performance_framework.git' }
                              branch('main')
                          }
                      }
                      scriptPath(j.path)
                  }
              }
          }
      }
