jenkins:
  systemMessage: "Jenkins on k8s"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true

unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - script: |
      def gitUrl = 'https://github.com/youketero/k8s_performance_framework.git'
      def gitBranch = 'main'
      def folders = ['jmeter', 'k6', 'eck', 'fastapp']
      folders.each { j ->
        folder(j) {
            description('Jobs for ${j}')
        }
      }
      def jobs = [
          [name: 'deploy_eck', path: 'jenkins/jobs/deploy_eck.Jenkinsfile', folder: 'eck'],
          [name: 'stop_eck', path: 'jenkins/jobs/stop_eck.Jenkinsfile', folder: 'eck'],
          [name: 'deploy_jmeter_cluster', path: 'jenkins/jobs/deploy_jmeter_cluster.Jenkinsfile', folder: 'jmeter'],
          [name: 'stop_jmeter_cluster', path: 'jenkins/jobs/stop_jmeter_cluster.Jenkinsfile', folder: 'jmeter'],
          [name: 'start_jmeter_test', path: 'jenkins/jobs/start_jmeter_test.Jenkinsfile', folder: 'jmeter'],
          [name: 'stop_jmeter_test', path: 'jenkins/jobs/stop_jmeter_test.Jenkinsfile', folder: 'jmeter'],
          [name: 'deploy_stop_fastapp', path: 'jenkins/jobs/deploy_stop_fastapp.Jenkinsfile', folder: 'fastapp'],
          [name: 'stop_k6_cluster', path: 'jenkins/jobs/stop_k6_cluster.Jenkinsfile', folder: 'k6'],
          [name: 'deploy_k6_cluster', path: 'jenkins/jobs/deploy_k6_cluster.Jenkinsfile', folder: 'k6'],
          [name: 'start_k6_test', path: 'jenkins/jobs/start_k6_test.Jenkinsfile', folder: 'k6']
      ]
      jobs.each { j ->
          def job = j.folder + '/' + j.name
          pipelineJob(job) {
              description("Pipeline job ${j.name} created automatically by Seed Job")
              definition {
                  cpsScm {
                      scm {
                          git {
                              remote { url(gitUrl) }
                              branch(gitBranch)
                          }
                      }
                      scriptPath(j.path)
                  }
              }
          }
      }
