# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: performance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi