# Service for access to jenkins from browser
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: performance
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
