apiVersion: batch/v1
kind: Job
metadata:
  name: clean-jmeter-pvc
spec:
  ttlSecondsAfterFinished: 60 
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cleaner
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            echo "Cleaning jmeter pvc"
            rm -rf /jmeter/*
        volumeMounts:
          - name: jmeter-logs
            mountPath: /jmeter
      volumes:
        - name: jmeter-logs
          persistentVolumeClaim:
            claimName: jmeter-logs-pvc
