#Deployment for elasticsearch service
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: performance
spec:
  version: 8.13.4
  auth:
    roles:
      - secretName: logstash-roles-secret
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false